

\section{Motivation}

% elaborate on single cell variability and talk about the setup: an RNA-seq sample from a single population at a single time.
\begin{frame}{Single cell variability and differentiation}
Intrinsic variability between cells and measurement error - noise.

Differential expression of genes steering differentiation - signal.

% Need to think about differentiation and how it is reflected in gene expression
Continuous vs. abrupt, switch like gene expression change.
\end{frame}


\begin{frame}{Questions}
Which genes change in their expression due to differentiation?

Given a single cell, what is it's developmental stage?

-> Retrieve the hidden temporal ordering of cells.
\end{frame}

% So practically, what we want to do
\begin{frame}{Setup}
RNA-seq measurements from a cell population at one or multiple time points.

Visualize differentiation by aligning the cells along the differentiation trajectories.
\end{frame}


\section{Statistical Model}
\begin{frame}{Notation}
Let $n$ be the number of all cells and $G$ the number of all genes measured.

$\mathbf{x}$ is the position of the cell in the multi-dimensional space $\mathbb{R}^{G}$

Isotropic gaussian wave function:

\begin{figure}
\centering
  \includegraphics[width=0.5\linewidth]{Gaussianwave.png}
\end{figure}
\end{frame}


\begin{frame}{Markov chain transition probability matrix}
Two state markov chain:
\vspace{5mm}

$\left( \begin{array}{cc} 0 & 1 \\ 1 & 0 \end{array} \right)$
\hspace{1 cm}
\vspace{-1.6cm}
\begin{figure}
  \includegraphics[width=0.25\linewidth]{MC1.png}
\end{figure}

\vspace{5mm}
$\left( \begin{array}{cc} 0.3 & 0.7 \\ 0.2 & 0.8 \end{array} \right)$
\hspace{1 cm}
\vspace{-1.6cm}
\begin{figure}
  \includegraphics[width=0.34\linewidth]{MC2.png}
\end{figure}

\vspace{10mm}

Transition probability:
% Show here the intersection function between two gaussian wave functions 
\end{frame}
% Add that the diagonal is set to 0 and the t.ps have to be normalised
% The t'th power of P will then define a random walk (diffusion) process of length n

\begin{frame}{Diffusion}
Diffusion distance: euclidian distance in the eigenvector space.

Diffusion coefficients: eigenvalues in the direction of their corresponding eigenvectors

Assumption: Eigenvalues drop to a noise level after the first $l$ components.
\end{frame}


\begin{frame}{Summary}
Similarly to the random fluctuation in real cells, we allow the cells to diffuse in $\mathbb{R}^{G}$

Output: Main 'diffusion' directions.
\end{frame}

% More practical aspects
\begin{frame}{Missing Values}
% Include Gaussian Wave

Decompose the kernel of the gaussian wave into $G$ components.

Replace missing values with hypothetical distribution.

Choice of a gaussian distribution may be preferred over uniform distribution due to computational reasons.
\end{frame}

\begin{frame}{Determination of the Gaussian Kernel Width}
% Include Interference Function - s too big, no sensitivity, s too small, no ergodicity

The average dimensionality of the manifold is equal to 

%Insert formula

When the average dimensionality decreases after a maximum, 
\end{frame}

